Add queue support to mediaPlayer
bcc-code/bmm-web pull request #104
Opened 2023-05-02 18:58 UTC by u12206050

Add shuffle to easy test queue
Add next and previous to composable, not sure if we have a need for it yet.

2023-05-03 07:12 UTC, SimonSimCity commented
LGTM as a first draft. I'd further on try decoupling the queue from the player while keeping them as a single interface on the plugin. This way we can have an easier time testing while maintaining an easy 2 use interface.

Please let prettier and eslint do their job and I'm fine with merging it in.

@kkuepper maybe good to streamline the source logic with what's in the app already, so the UX is equal?

2023-05-03 07:50 UTC, u12206050 commented
@SimonSimCity Havn't done anything to hinder prettier and linting, although it doesn't seem to work when I run `pnpm lint` is there something in the install or script missing, alternatively some missing steps in README. Ideally anyone starting off with the project should have everything working out of the box when following README steps.
Maybe we can take a look at it tonight.

2023-05-03 07:56 UTC, u12206050 commented
btw, what is up with all the weird file names `3.mediaPlayer` etc?

2023-05-03 12:03 UTC, SimonSimCity commented
> it doesn't seem to work when I run `pnpm lint` [...]

Well, that's for checking. All linting should work out of the box when using vscode and the recommended extensions. If you disabled auto-run of prettier when saving, you'll (obviously) have to run it on your own, which seems to be the case in your env.

Have to check if I can make it to WWW tonight.

> btw, what is up with all the weird file names `3.mediaPlayer` etc?

If you mean the prefix of numbers, that's the nuxt-way to ensure plugins are loaded after those they depend on: https://nuxt.com/docs/guide/directory-structure/plugins#plugin-registration-order

2023-05-03 13:33 UTC, SimonSimCity requested changes
Looking through the action-flow, this looks rather superficially implemented, just supporting one use-case 🧐 We can merge this, but I'll take this apart later either way to support more use-cases, which might require a full refactoring of the code merged in here...

2023-05-03 13:33 UTC, SimonSimCity commented on plugins/3.mediaPlayer.ts
> +    // Play if currently paused and no track is playing
I guess I'll have to rip this apart in another PR... I can just come up with all to many scenarios where this wouldn't be what a user would expect to happen... E.g. when playing some songs but clicking on a song of an album ...

2023-05-03 15:49 UTC, kkuepper commented on pages/playlist/curated/[id].vue
> +    shuffledTracks.forEach((track) => addTrackToQueue(track));
I think we need a way to add multiple tracks to the queue at once.
Something like:
playTracks(Track currentTrack, List<Track> queue)

2023-05-03 15:49 UTC, kkuepper commented on pages/playlist/curated/[id].vue
> +    shuffledTracks.forEach((track) => addTrackToQueue(track));
But I think this PR did what it wanted to achieve and further steps can be done in a separate PR.

2023-05-05 14:45 UTC, kkuepper commented
@SimonSimCity I would merge this and do further changes in a separate PR. Is that ok?

2023-05-08 08:42 UTC, SimonSimCity commented
@kkuepper I agree after resolving my question about the changes in the `.gitignore` file. Those changes, to me, are a sign of that the environment is not set up for DX with nuxt but for speeding up things which can not properly be done in a nuxt-env.

2023-05-23 19:45 UTC, kkuepper commented
reverted .gitignore and made pnpm lint pass.
@SimonSimCity If you or someone else doesn't complain the next few hours, I'll merge this PR.

2023-05-24 06:55 UTC, SimonSimCity approved these changes

2023-05-24 06:56 UTC, SimonSimCity commented
Merging it. https://github.com/bcc-code/bmm-web/pull/104#pullrequestreview-1410900159 should be picked up in a separate PR then.

2023-05-24 06:56 UTC, merged